runtime: php55
api_version: 1

handlers:
- url: /.*
  script: wwMainApp.php
  
- url: /wwMonitor.js
  script: wwMonitor.js
  
- url: /wwTaskAppend.js
  script: wwTaskAppend.js

- url: /wwTaskAppend.js
  script: wwTaskAppend.js
